[tool.black]
line-length = 119
target-version = ['py310', 'py311', 'py312']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3

[tool.mypy]
disable_error_code = ["import-untyped", "import-not-found"]
files = [
    "seleniumwire2"
]