name: build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip
      - run: pip install tox
      - run: tox -e isort

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - run: python -m pip install --upgrade pip
    - run: pip install tox
    - run: tox -e black

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - run: python -m pip install --upgrade pip
    - run: pip install tox
    - run: tox -e flake8

  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            py: '3.12'
          - os: macos-latest
            py: '3.12'
          - os: ubuntu-latest
            py: '3.12'
          - os: ubuntu-latest
            py: '3.11'
          - os: ubuntu-latest
            py: '3.10'
    runs-on: ${{ matrix.os }}
    steps:
      - run: printenv
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - run: pip install tox
      - run: tox -e py
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  end2end_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 125
          install-chromedriver: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - run: pip install tox
      - run: tox -e e2e
        env:
          CHROMIUM_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
